[mcp_servers.Context7]
command = "npx"
args = ["-y", "upstash/context7-mcp@latest"]

[mcp_servers.sequentialthinking]
command = "npx"
args = ["-y", "modelcontextprotocol/server-sequential-thinking"]
disabled = false
autoApprove = []